export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';

export const LOGOUT = 'USERS_LOGOUT';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const AUTHORIZATIONS_REQUEST = 'AUTHORIZATIONS_REQUEST';
export const AUTHORIZATIONS_SUCCESS = 'AUTHORIZATIONS_SUCCESS';
export const AUTHORIZATIONS_ERROR = 'AUTHORIZATIONS_ERROR';